server:
  port: 8080

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  check-config-location: true

spring:
  profiles:
    active: dev

sqlServer:
    parameterCount: 2000



